name: species
description: A new Flutter project.

publish_to: "none" 


version: 1.0.2+6

environment:
  sdk: ">=3.1.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.3
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.16.0
  go_router: ^7.1.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  staggered_grid_view_flutter: ^0.0.4
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  rxdart: ^0.27.7
  just_audio: ^0.9.35
  just_audio_cache: ^0.1.2
  audio_video_progress_bar: ^2.0.1
  share_plus: ^7.2.1
  flutter_file_downloader: ^1.2.1
  permission_handler: ^11.0.1
  pdf: ^3.10.4
  printing: ^5.10.3
  flutter_launcher_icons: ^0.13.1
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.9
  animated_custom_dropdown: ^2.0.0
  lottie: ^2.7.0
  image_picker: ^1.0.4
  firebase_storage: ^11.4.1
  firebase_app_check: ^0.2.1+3
  flutter_multi_formatter: ^2.11.16
  url_launcher: ^6.2.1
  provider: ^6.1.1
  freezed: ^2.4.7
  build_runner: ^2.4.8
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  persistent_bottom_nav_bar: ^5.0.2
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  slang_build_runner: ^3.30.0
  intl: ^0.20.2
  remove_diacritic: ^0.9.0
  cloudinary: ^1.2.0
  syncfusion_flutter_pdf: ^24.1.41
  flutter_map: ^6.1.0
  path_provider: ^2.1.3
  flutterflow_paginate_firestore: ^1.0.3+1
  dartz: ^0.10.1
  intl_phone_field: ^3.2.0
  flutter_fortune_wheel: ^1.3.1
  word_search_safety: ^0.1.2-nullsafety.1
  audioplayers: ^5.2.1
  stroke_text: ^1.0.0
  chat_bubbles: ^1.5.0
  win32: ^5.2.0
  flutter_dotenv: ^6.0.0
  shake: ^3.0.0
  firebase_analytics: ^10.10.7
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#2196F3"
  image: assets/images/logo.png
  color_dark: "#2196F3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"




flutter:

  uses-material-design: true

  assets:
    - assets/splash/
    - .env
    - assets/images/
    - assets/lotties/
    - assets/staff/
    - assets/icons/
    - assets/icons/species/
    - assets/icons/species/images_icons/
    - assets/gifs/
    - assets/memory/
    - assets/memory/fruit/Nivel 1/
    - assets/memory/fruit/Nivel 2/
    - assets/memory/fruit/Nivel 3/
    - assets/memory/fruit/Nivel 4/
    - assets/memory/icon/
    - assets/memory/animation/
    - assets/memory/sounds/
    - assets/relacionaEspecie/
    - assets/puzzle/
    - assets/sounds/
    - assets/json/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/species/CustomIcons.ttf
