// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9GoDoTiArT8klYjbnPdHCw1ZSXQXWccU',
    appId: '1:750264368267:web:404d7f29506499be18e88e',
    messagingSenderId: '750264368267',
    projectId: 'guiailustrada-75ebe',
    authDomain: 'guiailustrada-75ebe.firebaseapp.com',
    storageBucket: 'guiailustrada-75ebe.appspot.com',
    measurementId: 'G-0Q8FL8H4JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZvLS-R43_UuA84Qs_eYxVWppvWaP30Pk',
    appId: '1:750264368267:android:0dc61fea05ad312a18e88e',
    messagingSenderId: '750264368267',
    projectId: 'guiailustrada-75ebe',
    storageBucket: 'guiailustrada-75ebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSfiq6CteHwYg5A8tlDySBonHCgCkXxoY',
    appId: '1:750264368267:ios:194b844d98f06a3b18e88e',
    messagingSenderId: '750264368267',
    projectId: 'guiailustrada-75ebe',
    storageBucket: 'guiailustrada-75ebe.appspot.com',
    iosBundleId: 'pe.gob.iiap.guiailustrada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSfiq6CteHwYg5A8tlDySBonHCgCkXxoY',
    appId: '1:750264368267:ios:8f7b050a1c54fb9718e88e',
    messagingSenderId: '750264368267',
    projectId: 'guiailustrada-75ebe',
    storageBucket: 'guiailustrada-75ebe.appspot.com',
    iosBundleId: 'pe.gob.iiap.species.RunnerTests',
  );
}
